//
// Created by vladimir on 29/10/17.
//

#ifndef CRACKINGTHECODINGINTERVIEW_THREESTACKS_H
#define CRACKINGTHECODINGINTERVIEW_THREESTACKS_H


class ThreeStacks {
    // TODO
};


#endif //CRACKINGTHECODINGINTERVIEW_THREESTACKS_H
